### PR TITLE
Remove MR  mapping for cloud run and cloud functions

### LINKED ISSUE #248: Metrics exporter does not support Cloud Run
If we attempt to use this with cloud run, it doesn't work:

```
shadow.com.google.api.gax.rpc.InvalidArgumentException: shadow.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.
	at shadow.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
	at shadow.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:98)
	at shadow.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at shadow.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at shadow.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at shadow.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at shadow.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at shadow.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at shadow.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at shadow.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at shadow.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
	at shadow.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at shadow.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at shadow.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at shadow.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at shadow.com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
	at shadow.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at shadow.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at shadow.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at shadow.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at shadow.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at shadow.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: shadow.com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at shadow.com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at shadow.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at shadow.com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1729)
		at shadow.com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1661)
		at shadow.com.google.cloud.opentelemetry.metric.CloudMetricClientImpl.createTimeSeries(CloudMetricClientImpl.java:40)
		at shadow.com.google.cloud.opentelemetry.metric.InternalMetricExporter.createTimeSeriesBatch(InternalMetricExporter.java:219)
		at shadow.com.google.cloud.opentelemetry.metric.InternalMetricExporter.export(InternalMetricExporter.java:204)
		at shadow.com.google.cloud.opentelemetry.metric.GoogleCloudMetricExporter.export(GoogleCloudMetricExporter.java:90)
		at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.doRun(PeriodicMetricReader.java:162)
		at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.run(PeriodicMetricReader.java:148)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
		... 3 more
Caused by: shadow.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_revision. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.
	at shadow.io.grpc.Status.asRuntimeException(Status.java:539)
	... 14 more
```

### PR DESCRIPTION
**Pull request by psx95**
Fix #248 

This PR removes the explicit mapping to following Monitored Resource Types:
 - cloud_run_revision 
 - cloud_function
 
These mappings are removed since these MR types [do not support user-defined metrics](https://cloud.google.com/monitoring/custom-metrics). By removing their mappings, the exporter will by default map them to generic_task. 

The PR also adds a convenience script that allows autoinstrument example to be able to run in cloud-run environment. 

*This script was used to verify that metrics can be sent from a cloud-run environment and they appear in Cloud Monitoring under Generic Task* 

Similar to work already done in - https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/570

### CODE REVIEW

File: examples/autoinstrument/run_in_cloud-run.sh [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+fi
+
+echo "ENVIRONMENT VARIABLES VERIFIED"
+
+echo "CREATING CLOUD ARTIFACT REPOSITORY"
+gcloud artifacts repositories create ${CONTAINER_REGISTRY} --repository-format=docker --location=${REGISTRY_LOCATION} --description="Sample applications to run on Google Cloud Run"
+echo "CREATED ${CONTAINER_REGISTRY} in ${REGISTRY_LOCATION}"
+
+echo "BUILDING SAMPLE APP IMAGE"
+gradle clean jib --image "${REGISTRY_LOCATION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/${CONTAINER_REGISTRY}/hello-autoinstrument-java"
```
Comment (punya) [inline examples/autoinstrument/run_in_cloud-run.sh:42]: Consider factoring out the fully qualified image name into a variable so you can use it twice.

```sh
IMAGE="${REGISTRY_LOCATION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/${CONTAINER_REGISTRY}/hello-autoinstrument-java"
```

File: shared/resourcemapping/src/main/java/com/google/cloud/opentelemetry/resource/ResourceTranslator.java [hunk 2]
```diff
@@ -70,50 +71,43 @@ public static AttributeMapping create(
   }
 
   private static List<AttributeMapping> GCE_INSTANCE_LABELS =
-      java.util.Arrays.asList(
+      Arrays.asList(
```
Comment (punya) [inline shared/resourcemapping/src/main/java/com/google/cloud/opentelemetry/resource/ResourceTranslator.java:74]: In future, please keep cosmetic changes/cleanup in a separate PR.

File: examples/autoinstrument/run_in_cloud-run.sh [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+
+if [[ -z "${GOOGLE_CLOUD_RUN_REGION}" ]]; then
+  echo "GOOGLE_CLOUD_RUN_REGION environment variable not set"
+  exit 1
+fi
+
+echo "ENVIRONMENT VARIABLES VERIFIED"
+
+echo "CREATING CLOUD ARTIFACT REPOSITORY"
+gcloud artifacts repositories create ${CONTAINER_REGISTRY} --repository-format=docker --location=${REGISTRY_LOCATION} --description="Sample applications to run on Google Cloud Run"
```
[the remark this answers is not in the document]
Comment (psx95) [reply examples/autoinstrument/run_in_cloud-run.sh:38]: It will warn that the repo already already exists and continue. I ran the example multiple times through the script.

File: examples/autoinstrument/README.md [hunk 4]
```diff
@@ -53,6 +53,42 @@ Or, if you'd like to synthesize a parent trace:
...
+```shell
+# This can be any supported Google cloud region
+export GOOGLE_CLOUD_RUN_REGION=us-central1
+```
+
+Then, from the root of the repository,
+```shell
+cd examples/autoinstrument && ./run_in_cloud-run.sh
+```
+This will deploy the containerized application to Cloud Run and you will be presented with a service URL which would look something like -
```
[the remark this answers is not in the document]
Comment (psx95) [reply examples/autoinstrument/README.md:71]: Done.

File: examples/autoinstrument/README.md [hunk 5]
```diff
@@ -53,6 +53,40 @@ Or, if you'd like to synthesize a parent trace:
...
+Then, from the root of the repository,
+```shell
+cd examples/autoinstrument && ./run_in_cloud-run.sh
+```
+This will deploy the containerized application to Cloud Run and you will be presented with a service URL which would look something like - 
+
+```text
+Service URL: https://hello-autoinstrument-cloud-run-m43qtxry5q-uc.a.run.app
+```
+
```
Comment (punya) [inline examples/autoinstrument/README.md:76]: Now that we're using the proxy, the service URL should no longer matter right?

File: examples/autoinstrument/README.md [hunk 6]
```diff
@@ -53,6 +53,40 @@ Or, if you'd like to synthesize a parent trace:
...
+Once the Cloud Run service is deployed, run:
+
+```shell
+gcloud beta run services proxy hello-autoinstrument-cloud-run --port=8080
+```
+
+This will allow you to call the service from your browser via localhost -
```
Comment (punya) [inline examples/autoinstrument/README.md:83]: Might still want to give them curl instructions in case they're running in a headless environment like Cloud Shell. (In general most of our example instructions should be tuned for Cloud Shell.)

Comment (psx95) [reply examples/autoinstrument/README.md:83]: Yeah, I was in two minds about that, I will add that back.

File: examples/autoinstrument/README.md (hunk 5 above)
Comment (psx95) [reply examples/autoinstrument/README.md:76]: Yes, this is just to clarify what to expect in case of a successful deployment.

**Comment by Eden90** [comment]
When is planned release with these changes?
