### PR TITLE
Fix exporter-trace example & add README

### LINKED ISSUE #205: Fix exporter-trace example
The current exporter-trace example (under examples directory) crashes on running. 

Address the TODOs and fix the example.

### PR DESCRIPTION
**Pull request by psx95**
Fixes #205 .

### CODE REVIEW

File: examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java [hunk 1]
```diff
@@ -17,23 +17,23 @@
...
 import io.opentelemetry.sdk.trace.export.SpanExporter;
 import java.time.Duration;
 import java.util.Random;
+import java.util.concurrent.TimeUnit;
 
 public class TraceExporterExample {
-  // TODO: Update this to NON-global OpenTelemetry.  Only APIs/Frameworks should be using global.
-  private static final Tracer tracer =
-      GlobalOpenTelemetry.getTracer("io.opentelemetry.example.TraceExporterExample");
+  private static final String INSTRUMENTATION_SCOPE_NAME = TraceExporter.class.getName();
```
Comment (jsuereth) [inline examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java:32]: NIt: This should be the TraceExporterExample, to match what was there previously.

**Review by jsuereth — APPROVED** [review]
One nit, but pretty important for an example.  We don't want folks attachign trace instrumentation against our Exporter class.

**Comment by psx95** [comment]
> One nit, but pretty important for an example. We don't want folks attachign trace instrumentation against our Exporter class.

Agreed, I updated it.
